### ISSUE TITLE
[Poll] The system must allow to group arbitrary many items into one poll

### ISSUE THREAD

**Issue by patrick-nits** [ndea/java-EE-sose-15#9]
The model **Poll** must *have many* **Items** through **Groups**.
The model **Item** must *belong to* a **Poll** through a **Group**.
The model **Poll** must *have many* **Groups**. 

@artschie1337 @irbisKo @ndea @keslerjulia 
Is this this interpretation of the requirement correct? Discussion welcome.

**Comment by irbisKo** [comment]
I think, those interpretation make sense.but please explain:
what exactly the function of a Group? who executes them? organizers?
Do you mean this requirements?
1.6.The system must allow to group arbitrary many items into one poll. MANDATORY

**Comment by ndea** [comment]
Seems like a reasonable approach. One can create a poll with many groups. A group therefore contains many items. So its possible to build a poll with more than one topic. I guess this would meet the requirements.
